### ISSUE TITLE
Max Buffer Length Exceeded: attribValue

### ISSUE THREAD

**Issue by NeilCresswell** [Workshape/icon-font-generator#20]
Occurs when processing an .svg file with a very large path statement.
(In this case one of my files is 133KB long. Not an issue on more typically-sized .svg files.)

**Comment by tancredi** [comment]
Not sure, sounds like an issue with [webfonts-generator](https://github.com/sunflowerdeath/webfonts-generator) maybe worth opening another issue there?

**Comment by perexwi** [comment]
Hi, i had the same issue with some svg files larger than 133KB.

**Output:**

> Error: Max buffer length exceeded: attribValue
> Line: 281
> Column: 186195
> Char: 
>&nbsp;&nbsp;&nbsp;&nbsp;at error (/usr/lib/node_modules/icon-font-generator/node_modules/sax/lib/sax.js:651:10)
>&nbsp;&nbsp;&nbsp;&nbsp;at checkBufferLength (/usr/lib/node_modules/icon-font-generator/node_modules/sax/lib/sax.js:125:13)
>&nbsp;&nbsp;&nbsp;&nbsp;at SAXParser.write (/usr/lib/node_modules/icon-font-generator/node_modules/sax/lib/sax.js:1505:7)
>&nbsp;&nbsp;&nbsp;&nbsp;at SAXStream.write (/usr/lib/node_modules/icon-font-generator/node_modules/sax/lib/sax.js:239:18)
>&nbsp;&nbsp;&nbsp;&nbsp;at ReadStream.ondata (_stream_readable.js:708:22)
>&nbsp;&nbsp;&nbsp;&nbsp;at ReadStream.emit (events.js:315:20)
>&nbsp;&nbsp;&nbsp;&nbsp;at addChunk (_stream_readable.js:297:12)
>&nbsp;&nbsp;&nbsp;&nbsp;at readableAddChunk (_stream_readable.js:273:9)
>&nbsp;&nbsp;&nbsp;&nbsp;at ReadStream.Readable.push (_stream_readable.js:214:10)
>&nbsp;&nbsp;&nbsp;&nbsp;at internal/fs/streams.js:242:14

> Emitted 'error' event on SVGIcons2SVGFontStream instance at:
>&nbsp;&nbsp;&nbsp;&nbsp;at SAXStream.svgicons2svgfontSaxErrorCb (/usr/lib/node_modules/icon-font-generator/node_modules/svgicons2svgfont/src/index.js:251:13)
>&nbsp;&nbsp;&nbsp;&nbsp;at SAXStream.emit (events.js:327:22)
>&nbsp;&nbsp;&nbsp;&nbsp;at SAXParser.SAXStream._parser.onerror (/usr/lib/node_modules/icon-font-generator/node_modules/sax/lib/sax.js:194:10)
>&nbsp;&nbsp;&nbsp;&nbsp;at emit (/usr/lib/node_modules/icon-font-generator/node_modules/sax/lib/sax.js:624:35)
>&nbsp;&nbsp;&nbsp;&nbsp;at error (/usr/lib/node_modules/icon-font-generator/node_modules/sax/lib/sax.js:653:5)
>&nbsp;&nbsp;&nbsp;&nbsp;at checkBufferLength (/usr/lib/node_modules/icon-font-generator/node_modules/sax/lib/sax.js:125:13)
>&nbsp;&nbsp;&nbsp;&nbsp;[... lines matching original stack trace ...]
>&nbsp;&nbsp;&nbsp;&nbsp;at ReadStream.emit (events.js:315:20)


**I fixed it** editing the sax.js file in /usr/lib/node_modules/icon-font-generator/node_modules/sax/lib/sax.js

1. Find sax.MAX_BUFFER_LENGTH line, in my file i had 64 * 1024
2. So remove the "64 * 1024" and i changed it for 999999. So now the line has sax.MAX_BUFFER_LENGTH = 999999
3. Then i saved the file and that is all. Working

**Comment by decarvalholucas** [comment]
I have the same problem.

**Comment by perexwi** [comment]
> I have the same problem.

Hello, look at my previous comment. Maybe that works for you.
https://github.com/Workshape/icon-font-generator/issues/20#issuecomment-617970585

**Comment by geisels** [comment]
I have the same problem using in Linux Mint 20.2.
