### ISSUE TITLE
Unexpected token error when trying simple use case

### ISSUE THREAD

**Issue by arochettesteinberg** [Workshape/icon-font-generator#75]
Hi,

I've been trying to convert a very simple set of SVG into a font using your tool but I keep running into the same error.

`icon-font-generator *.svg --out icon`
Always results in:

`\AppData\Roaming\npm\node_modules\icon-font-generator\bin\icon-font-generator:7
const { removeUndefinedKeys } = require('../lib/utils')
      ^
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3`

I've got ruby 2.6.6 installed on my Win10 machine.

Any clue?

Thank you very much!

**Comment by arochettesteinberg** [comment]
Mac OS doesn't bring much better results (running with ruby 2.3.3)
`/usr/local/lib/node_modules/icon-font-generator/lib/index.js:29
async function generate(options = {}) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:545:28)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/icon-font-generator/bin/icon-font-generator:8:23)
    at Module._compile (module.js:573:32)
`

Wonder what I'm doing wrong here.
